allowBuilds:
  better-sqlite3: true
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/vite-plugin@1.56.0'
  - '@types/node@26.6.2'
  - dotenv@18.0.1
  - eslint@10.11.0
  - miniflare@5.20260918.0-alpha
  - wrangler@4.135.0
  - '@milkdown/components@7.22.2'
  - '@milkdown/core@7.22.2'
  - '@milkdown/ctx@7.22.2'
  - '@milkdown/exception@7.22.2'
  - '@milkdown/kit@7.22.2'
  - '@milkdown/plugin-block@7.22.2'
  - '@milkdown/plugin-clipboard@7.22.2'
  - '@milkdown/plugin-cursor@7.22.2'
  - '@milkdown/plugin-diff@7.22.2'
  - '@milkdown/plugin-history@7.22.2'
  - '@milkdown/plugin-indent@7.22.2'
  - '@milkdown/plugin-listener@7.22.2'
  - '@milkdown/plugin-slash@7.22.2'
  - '@milkdown/plugin-streaming@7.22.2'
  - '@milkdown/plugin-tooltip@7.22.2'
  - '@milkdown/plugin-trailing@7.22.2'
  - '@milkdown/plugin-upload@7.22.2'
  - '@milkdown/preset-commonmark@7.22.2'
  - '@milkdown/preset-gfm@7.22.2'
  - '@milkdown/prose@7.22.2'
  - '@milkdown/transformer@7.22.2'
  - '@milkdown/utils@7.22.2'
