/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedAppRouteImport } from './routes/_authed/_app'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as AuthedAppHomeRouteImport } from './routes/_authed/_app/home'
import { Route as AuthedAppNotesRouteImport } from './routes/_authed/_app/notes'
import { Route as AuthedAppSettingsRouteImport } from './routes/_authed/_app/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedAppNotesIndexRouteImport } from './routes/_authed/_app/notes/index'
import { Route as AuthedAppNotesNoteIdRouteImport } from './routes/_authed/_app/notes/$noteId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const AuthedAppHomeRoute = AuthedAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppNotesRoute = AuthedAppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSettingsRoute = AuthedAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedAppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppNotesIndexRoute = AuthedAppNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppNotesRoute,
} as any)
const AuthedAppNotesNoteIdRoute = AuthedAppNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AuthedAppNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/login': typeof LoginRoute
  '/home': typeof AuthedAppHomeRoute
  '/notes': typeof AuthedAppNotesRouteWithChildren
  '/settings': typeof AuthedAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/notes/$noteId': typeof AuthedAppNotesNoteIdRoute
  '/notes/': typeof AuthedAppNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/login': typeof LoginRoute
  '/home': typeof AuthedAppHomeRoute
  '/settings': typeof AuthedAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/notes/$noteId': typeof AuthedAppNotesNoteIdRoute
  '/notes': typeof AuthedAppNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/_app': typeof AuthedAppRouteWithChildren
  '/_site/': typeof SiteIndexRoute
  '/_authed/_app/home': typeof AuthedAppHomeRoute
  '/_authed/_app/notes': typeof AuthedAppNotesRouteWithChildren
  '/_authed/_app/settings': typeof AuthedAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/_app/notes/$noteId': typeof AuthedAppNotesNoteIdRoute
  '/_authed/_app/notes/': typeof AuthedAppNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/home'
    | '/notes'
    | '/settings'
    | '/api/auth/$'
    | '/notes/$noteId'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/home'
    | '/settings'
    | '/api/auth/$'
    | '/notes/$noteId'
    | '/notes'
  id:
    | '__root__'
    | '/_authed'
    | '/_site'
    | '/login'
    | '/_authed/_app'
    | '/_site/'
    | '/_authed/_app/home'
    | '/_authed/_app/notes'
    | '/_authed/_app/settings'
    | '/api/auth/$'
    | '/_authed/_app/notes/$noteId'
    | '/_authed/_app/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_authed/_app/home': {
      id: '/_authed/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedAppHomeRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/notes': {
      id: '/_authed/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthedAppNotesRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/settings': {
      id: '/_authed/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedAppSettingsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_app/notes/': {
      id: '/_authed/_app/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthedAppNotesIndexRouteImport
      parentRoute: typeof AuthedAppNotesRoute
    }
    '/_authed/_app/notes/$noteId': {
      id: '/_authed/_app/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AuthedAppNotesNoteIdRouteImport
      parentRoute: typeof AuthedAppNotesRoute
    }
  }
}

interface AuthedAppNotesRouteChildren {
  AuthedAppNotesNoteIdRoute: typeof AuthedAppNotesNoteIdRoute
  AuthedAppNotesIndexRoute: typeof AuthedAppNotesIndexRoute
}

const AuthedAppNotesRouteChildren: AuthedAppNotesRouteChildren = {
  AuthedAppNotesNoteIdRoute: AuthedAppNotesNoteIdRoute,
  AuthedAppNotesIndexRoute: AuthedAppNotesIndexRoute,
}

const AuthedAppNotesRouteWithChildren = AuthedAppNotesRoute._addFileChildren(
  AuthedAppNotesRouteChildren,
)

interface AuthedAppRouteChildren {
  AuthedAppHomeRoute: typeof AuthedAppHomeRoute
  AuthedAppNotesRoute: typeof AuthedAppNotesRouteWithChildren
  AuthedAppSettingsRoute: typeof AuthedAppSettingsRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppHomeRoute: AuthedAppHomeRoute,
  AuthedAppNotesRoute: AuthedAppNotesRouteWithChildren,
  AuthedAppSettingsRoute: AuthedAppSettingsRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface SiteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
